// ================================================================
// AUTO-GENERATED BY DESIGN TOKEN SYNC — DO NOT EDIT MANUALLY
// ================================================================
// Last synced : 2026-07-18T05:42:52.592Z
// Figma file  : unknown
// Collections : 1
// Variables   : 4
// ================================================================

export const tokens = {
  "color": {
    "primary": "#151410",
    "secondary": "#ffffff",
    "green": "#bdff00",
    "grey": "#d9d9d9"
  }
} as const;

// ─── Type helpers ────────────────────────────────────────────────

export type Tokens = typeof tokens;

export type TokenCollections = keyof Tokens;

