// ================================================================
// AUTO-GENERATED BY DESIGN TOKEN SYNC — DO NOT EDIT MANUALLY
// ================================================================
// Last synced : 2026-07-18T12:40:44.421Z
// Figma file  : unknown
// Collections : 2
// Variables   : 23
// ================================================================

export const tokens = {} as const;

export type Tokens = typeof tokens;
export type TokenCollections = keyof Tokens;
