// ================================================================
// AUTO-GENERATED BY DESIGN TOKEN SYNC — DO NOT EDIT MANUALLY
// ================================================================
// Last synced : 2026-07-18T07:51:48.238Z
// Figma file  : unknown
// Collections : 1
// Variables   : 7
// ================================================================

export const tokens = {
  "color": {
    "primary": "#151410",
    "secondary": "#ffffff",
    "green": "#bdff00",
    "grey": "#d9d9d9",
    "sample": "#ffffff",
    "sample2": "#ffffff",
    "asdas": "#a55252"
  }
} as const;

// ─── Type helpers ────────────────────────────────────────────────

export type Tokens = typeof tokens;

export type TokenCollections = keyof Tokens;

