// ================================================================
// AUTO-GENERATED BY DESIGN TOKEN SYNC — DO NOT EDIT MANUALLY
// ================================================================
// Last synced : 2026-07-18T14:23:26.888Z
// Figma file  : unknown
// Collections : 2
// Variables   : 4
// ================================================================

export const tokens = {
  "tokens": {
    "space": {
      "button": {
        "padding": {
          "x": 4,
          "y": 4
        }
      }
    }
  },
  "primitives": {
    "spacing": {
      "0": 0,
      "2": 2,
      "4": 4,
      "8": 8,
      "12": 12,
      "16": 16,
      "24": 24,
      "32": 32,
      "42": 42,
      "48": 48,
      "56": 56,
      "64": 64,
      "72": 72,
      "96": 96,
      "102": 102,
      "128": 128,
      "156": 156,
      "256": 256
    },
    "number": 0,
    "color": {
      "dark": "#151410",
      "light": "#ffffff",
      "limegreen": "#151410",
      "grey": "#7b7b7b"
    }
  }
} as const;

// ─── Type helpers ────────────────────────────────────────────────

export type Tokens = typeof tokens;

export type TokenCollections = keyof Tokens;

