// ================================================================
// AUTO-GENERATED BY DESIGN TOKEN SYNC — DO NOT EDIT MANUALLY
// ================================================================
// Last synced : 2026-07-18T13:04:41.430Z
// Figma file  : unknown
// Collections : 2
// Variables   : 25
// ================================================================

export const tokens = {
  "tokens": {
    "spaceButtonPaddingX": 4,
    "spaceButtonPaddingY": 4
  },
  "primitives": {
    "spacing0": 0,
    "number": 0,
    "spacing2": 2,
    "spacing4": 4,
    "spacing8": 8,
    "spacing12": 12,
    "spacing16": 16,
    "spacing24": 24,
    "spacing32": 32,
    "spacing42": 42,
    "spacing48": 48,
    "spacing56": 56,
    "spacing64": 64,
    "spacing72": 72,
    "spacing96": 96,
    "spacing102": 102,
    "spacing128": 128,
    "spacing156": 156,
    "spacing256": 256,
    "colorsDark": "#151410",
    "colorsLight": "#ffffff",
    "colorsLimegreen": "#151410",
    "colorsGrey": "#838383"
  }
} as const;

// ─── Type helpers ────────────────────────────────────────────────

export type Tokens = typeof tokens;

export type TokenCollections = keyof Tokens;

