// ================================================================
// AUTO-GENERATED BY DESIGN TOKEN SYNC — DO NOT EDIT MANUALLY
// ================================================================
// This file will be automatically updated when you sync from Figma.
// ================================================================

export const tokens = {} as const;

export type Tokens = typeof tokens;
export type TokenCollections = keyof Tokens;
